### ISSUE TITLE
Start crawl from hostname instead of specific sitemap

### ISSUE THREAD

**Issue by igobranco** [arquivo/dspace-link-extractor#3]
Instead of using a list of dspace instances that ends with "/sitemap?map=0" 
- It is best to start using the homepage;
- then inspect robots.txt 
- Navigate to Sitemap robots entries;
- Continue for more one op - iterating for a sitemap;
- view urls

**Comment by dcgomes** [comment]
We are now using the RCAAP API to get these data.
